ALTER TABLE usage_events ADD COLUMN IF NOT EXISTS input_cost_usd DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE usage_events ADD COLUMN IF NOT EXISTS output_cost_usd DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE usage_events ADD COLUMN IF NOT EXISTS cache_read_cost_usd DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE usage_events ADD COLUMN IF NOT EXISTS cache_write_cost_usd DOUBLE PRECISION NOT NULL DEFAULT 0;
