import { useEffect, useState } from 'react'
import { getAuditEvents, getOrganizations } from '../api/client'
import type { AuditEvent, AuditFilters, Organization } from '../api/contracts'
import { Badge, Empty, ErrorBanner, Field } from '../components/Management'
import { PageLoading } from '../components/PageState'
import { SearchableSelect } from '../components/SearchableSelect'
import { formatDateTime } from '../lib/format'

const initialFilters: AuditFilters = { organizationId: '', actorId: '', action: '', targetType: '', targetId: '', since: '', until: '' }
export function AuditPage() {
  const [filters, setFilters] = useState<AuditFilters>(() => ({ ...initialFilters, organizationId: new URLSearchParams(window.location.search).get('organization_id') ?? '' })); const [events, setEvents] = useState<AuditEvent[]>([]); const [organizations, setOrganizations] = useState<Organization[]>([]); const [cursor, setCursor] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [version, setVersion] = useState(0)
  useEffect(() => { void getOrganizations().then((response) => setOrganizations(response.data)).catch(() => setOrganizations([])) }, [])
  useEffect(() => { let live = true; setLoading(true); void getAuditEvents(filters).then((response) => { if (live) { setEvents(response.data); setCursor(response.next_cursor ?? '') } }).catch((reason: Error) => { if (live) setError(reason.message) }).finally(() => { if (live) setLoading(false) }); return () => { live = false } }, [filters, version])
  const set = (key: keyof AuditFilters, value: string) => setFilters((current) => ({ ...current, [key]: value }))
  const loadMore = () => void getAuditEvents(filters, cursor).then((response) => { setEvents((current) => [...current, ...response.data]); setCursor(response.next_cursor ?? '') }).catch((reason: Error) => setError(reason.message))
  return <><header className="page-header"><div><span className="eyebrow">Observe / Governance</span><h1>Audit events</h1><p>Administrative mutations with safe metadata only.</p></div></header><div className="filter-panel audit-filters"><div className="filter-row"><Field label="Organization"><SearchableSelect value={filters.organizationId} onChange={(value) => set('organizationId', value)} searchPlaceholder="Search organizations" options={[{ value: '', label: 'All visible organizations' }, ...organizations.map((organization) => ({ value: organization.id, label: organization.name, meta: `${organization.member_count ?? 0} members` }))]} /></Field><Field label="Action"><input value={filters.action} onChange={(event) => set('action', event.target.value)} placeholder="key.create" /></Field><Field label="Actor ID"><input value={filters.actorId} onChange={(event) => set('actorId', event.target.value)} /></Field><Field label="Target type"><input value={filters.targetType} onChange={(event) => set('targetType', event.target.value)} /></Field><Field label="Target ID"><input value={filters.targetId} onChange={(event) => set('targetId', event.target.value)} /></Field></div></div><ErrorBanner message={error} />{loading ? <PageLoading /> : events.length === 0 ? <Empty title="No audit events" detail="Try clearing filters or selecting another organization." /> : <section className="panel table-panel"><div className="table-scroll"><table className="management-table"><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Target</th><th>Organization</th><th>Metadata</th></tr></thead><tbody>{events.map((event) => { const metadata = Object.entries(event.safe_metadata ?? {}).map(([key, value]) => `${key}=${value}`).join(' · ') || '—'; return <tr key={event.id}><td>{formatDateTime(event.ts)}</td><td><strong title={event.actor_label || event.actor_type}>{event.actor_label || event.actor_type}</strong><small title={event.actor_id}>{event.actor_id}</small></td><td><Badge>{event.action}</Badge></td><td title={`${event.target_type} · ${event.target_id}`}>{event.target_type}<small>{event.target_id}</small></td><td title={event.organization_id || 'global'}>{event.organization_id || 'global'}</td><td className="wrap-cell" title={metadata}>{metadata}</td></tr> })}</tbody></table></div>{cursor && <div className="load-more"><button className="button secondary" onClick={loadMore}>Load older events</button></div>}</section>}<button hidden onClick={() => setVersion((value) => value + 1)} /></>
}
