import { useCallback, useEffect, useState } from 'react'
import { createAPIKey, deleteAPIKey, getAPIKeys, getModels, getOrganizations, getUsers, patchAPIKey, rotateAPIKey } from '../api/client'
import type { APIKey, ModelDefinition, Organization, User } from '../api/contracts'
import { Badge, Empty, ErrorBanner, Field } from '../components/Management'
import { Modal } from '../components/Modal'
import { PageLoading } from '../components/PageState'
import { SecretModal } from '../components/SecretModal'
import { useSession } from '../context/SessionContext'
import { formatDateTime } from '../lib/format'

const scopes = ['chat', 'usage:read', 'keys:manage', 'credentials:manage', 'models:manage', 'cache:purge', 'members:manage']

export function KeysPage() {
  const [keys, setKeys] = useState<APIKey[]>([]); const [models, setModels] = useState<ModelDefinition[]>([]); const [organizations, setOrganizations] = useState<Organization[]>([]); const [users, setUsers] = useState<User[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [creating, setCreating] = useState(false); const [editing, setEditing] = useState<APIKey | null>(null); const [secret, setSecret] = useState(''); const { session, isMaster } = useSession()
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [keyResponse, modelResponse, organizationResponse, userResponse] = await Promise.all([getAPIKeys(), getModels().catch(() => []), getOrganizations().catch(() => ({ object: 'list' as const, data: [] })), getUsers().catch(() => ({ object: 'list' as const, data: [] }))]); setKeys(keyResponse.data); setModels(modelResponse); setOrganizations(organizationResponse.data); setUsers(userResponse.data) } catch (reason) { setError((reason as Error).message) } finally { setLoading(false) } }, [])
  useEffect(() => { void load() }, [load])
  const toggle = async (key: APIKey) => { try { await patchAPIKey(key.id, { enabled: !key.enabled }); await load() } catch (reason) { setError((reason as Error).message) } }
  const rotate = async (key: APIKey) => { if (!window.confirm(`Rotate ${key.name}? The old secret will stop working immediately.`)) return; try { const response = await rotateAPIKey(key.id); setSecret(response.plaintext); await load() } catch (reason) { setError((reason as Error).message) } }
  const remove = async (key: APIKey) => { if (!window.confirm(`Delete ${key.name}?`)) return; try { await deleteAPIKey(key.id); await load() } catch (reason) { setError((reason as Error).message) } }
  return <><header className="page-header"><div><span className="eyebrow">Manage / Access</span><h1>API keys</h1><p>Ownership-aware keys with model allowlists, scopes, rate limits, and one-time secret delivery.</p></div><button className="button" onClick={() => setCreating(true)}>Create API key</button></header><ErrorBanner message={error} />{loading ? <PageLoading /> : keys.length === 0 ? <Empty title="No visible API keys" detail="Create a personal or organization-owned key." /> : <section className="panel table-panel"><div className="table-scroll"><table className="management-table"><thead><tr><th>Name</th><th>Owner</th><th>Context</th><th>Models</th><th>Scopes</th><th>Limits</th><th>Status</th><th /></tr></thead><tbody>{keys.map((key) => <tr key={key.id}><td><strong>{key.name}</strong><small>{key.key_prefix} · {formatDateTime(key.created_at)}</small></td><td>{key.owner_type}:{key.owner_user_id || key.owner_organization_id}</td><td>{key.context_organization_id || 'personal'}</td><td className="wrap-cell">{key.models.join(', ') || 'none'}</td><td className="wrap-cell">{key.scopes.join(', ')}</td><td>{key.quota_usd == null ? 'No quota' : `$${key.quota_usd}/${key.quota_period}`}<small>{key.rpm ? `${key.rpm} RPM` : 'No RPM limit'}</small></td><td><Badge tone={key.enabled ? 'good' : ''}>{key.enabled ? 'enabled' : 'disabled'}</Badge></td><td><div className="compact-actions"><button onClick={() => setEditing(key)}>Edit</button><button onClick={() => void toggle(key)}>{key.enabled ? 'Disable' : 'Enable'}</button><button onClick={() => void rotate(key)}>Rotate</button><button className="danger-text" onClick={() => void remove(key)}>Delete</button></div></td></tr>)}</tbody></table></div></section>}{(creating || editing) && <KeyModal existing={editing} models={models} organizations={organizations} users={users} session={session} isMaster={isMaster} onClose={() => { setCreating(false); setEditing(null) }} onSaved={(plaintext) => { setCreating(false); setEditing(null); if (plaintext) setSecret(plaintext); void load() }} />}{secret && <SecretModal secret={secret} title="One-time API key" onClose={() => setSecret('')} />}</>
}

function KeyModal({ existing, models, organizations, users, session, isMaster, onClose, onSaved }: { existing: APIKey | null; models: ModelDefinition[]; organizations: Organization[]; users: User[]; session: ReturnType<typeof useSession>['session']; isMaster: boolean; onClose: () => void; onSaved: (secret: string) => void }) {
  const [name, setName] = useState(existing?.name ?? ''); const [ownerType, setOwnerType] = useState(existing?.owner_type ?? (session?.principal_type === 'organization' ? 'organization' : 'user')); const [ownerUser, setOwnerUser] = useState(existing?.owner_user_id ?? session?.user_id ?? ''); const [ownerOrg, setOwnerOrg] = useState(existing?.owner_organization_id ?? session?.organization_id ?? ''); const [contextOrg, setContextOrg] = useState(existing?.context_organization_id ?? session?.organization_id ?? ''); const [selectedModels, setSelectedModels] = useState(existing?.models ?? []); const [selectedScopes, setSelectedScopes] = useState(existing?.scopes ?? ['chat']); const [quota, setQuota] = useState(existing?.quota_usd?.toString() ?? ''); const [quotaPeriod, setQuotaPeriod] = useState(existing?.quota_period ?? 'none'); const [rpm, setRPM] = useState(existing?.rpm?.toString() ?? ''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const toggleItem = (item: string, values: string[], setValues: (values: string[]) => void) => setValues(values.includes(item) ? values.filter((value) => value !== item) : [...values, item])
  const submit = async () => { setBusy(true); setError(''); try { const quotaValue = quota ? Number(quota) : null; const rpmValue = rpm ? Number(rpm) : null; if (existing) { await patchAPIKey(existing.id, { models: selectedModels, scopes: selectedScopes, quota_usd: quotaValue, quota_period: quotaPeriod, rpm: rpmValue }); onSaved('') } else { const organizationID = ownerType === 'organization' ? ownerOrg : ''; const response = await createAPIKey({ tenant_id: organizationID, name, models: selectedModels, scopes: selectedScopes, quota_usd: quotaValue, quota_period: quotaPeriod, rpm: rpmValue, owner_type: ownerType, owner_user_id: ownerType === 'user' ? ownerUser : '', owner_organization_id: organizationID, context_organization_id: ownerType === 'organization' ? organizationID : contextOrg }); onSaved(response.plaintext) } } catch (reason) { setError((reason as Error).message) } finally { setBusy(false) } }
  return <Modal title={existing ? `Edit ${existing.name}` : 'Create API key'} onClose={onClose}><ErrorBanner message={error} /><div className="form-grid"><Field label="Name"><input value={name} disabled={Boolean(existing)} onChange={(event) => setName(event.target.value)} /></Field>{isMaster && !existing && <Field label="Owner type"><select value={ownerType} onChange={(event) => setOwnerType(event.target.value)}><option value="user">User</option><option value="organization">Organization</option></select></Field>}{ownerType === 'user' && isMaster && !existing && <Field label="User owner"><select value={ownerUser} onChange={(event) => setOwnerUser(event.target.value)}><option value="">Choose user</option>{users.map((user) => <option value={user.id} key={user.id}>{user.username}</option>)}</select></Field>}{ownerType === 'organization' && !existing && <Field label="Organization owner"><select value={ownerOrg} onChange={(event) => setOwnerOrg(event.target.value)}><option value="">Choose organization</option>{organizations.map((organization) => <option value={organization.id} key={organization.id}>{organization.name}</option>)}</select></Field>}{ownerType === 'user' && !existing && <Field label="Organization context"><select value={contextOrg} onChange={(event) => setContextOrg(event.target.value)}><option value="">Personal</option>{organizations.map((organization) => <option value={organization.id} key={organization.id}>{organization.name}</option>)}</select></Field>}<Field label="Quota period"><select value={quotaPeriod} onChange={(event) => setQuotaPeriod(event.target.value)}><option value="none">No limit</option><option value="week">Weekly</option></select></Field><Field label="Quota USD"><input type="number" min="0" step="0.0001" value={quota} disabled={quotaPeriod === 'none'} onChange={(event) => setQuota(event.target.value)} /></Field><Field label="Requests/minute"><input type="number" min="1" value={rpm} onChange={(event) => setRPM(event.target.value)} /></Field></div><h3 className="form-section-title">Allowed models</h3><div className="option-grid">{models.map((model) => <label key={model.name}><input type="checkbox" checked={selectedModels.includes(model.name)} onChange={() => toggleItem(model.name, selectedModels, setSelectedModels)} /><span>{model.name}</span></label>)}</div><h3 className="form-section-title">Scopes</h3><div className="option-grid scopes">{scopes.map((scope) => <label key={scope}><input type="checkbox" checked={selectedScopes.includes(scope)} onChange={() => toggleItem(scope, selectedScopes, setSelectedScopes)} /><span>{scope}</span></label>)}</div><div className="dialog-actions"><button className="button" disabled={busy || (!existing && !name.trim()) || selectedScopes.length === 0} onClick={() => void submit()}>{existing ? 'Save key policy' : 'Create key'}</button></div></Modal>
}
