import { useCallback, useEffect, useState } from 'react'
import { addMember, createOrganization, deleteMember, getMembers, getOrganizations, getUsers, updateMember, updateOrganization } from '../api/client'
import type { Membership, Organization, User } from '../api/contracts'
import { Badge, Empty, ErrorBanner, Field } from '../components/Management'
import { Modal } from '../components/Modal'
import { PageLoading } from '../components/PageState'
import { SearchableSelect, TruncatedText } from '../components/SearchableSelect'
import { useSession } from '../context/SessionContext'
import { formatDateTime } from '../lib/format'

export function OrganizationsPage() {
  const { isMasterView, viewOrganizationID, has } = useSession(); const [items, setItems] = useState<Organization[]>([]); const [users, setUsers] = useState<User[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [creating, setCreating] = useState(false); const [membersFor, setMembersFor] = useState<Organization | null>(null)
  const load = useCallback(async () => { setLoading(true); try { const [organizations, userResponse] = await Promise.all([getOrganizations(), getUsers().catch(() => ({ object: 'list' as const, data: [] }))]); setItems(viewOrganizationID ? organizations.data.filter((organization) => organization.id === viewOrganizationID) : organizations.data); setUsers(userResponse.data) } catch (reason) { setError((reason as Error).message) } finally { setLoading(false) } }, [viewOrganizationID])
  useEffect(() => { void load() }, [load])
  const toggle = async (organization: Organization) => { try { await updateOrganization(organization.id, organization.name, organization.status === 'active' ? 'disabled' : 'active'); await load() } catch (reason) { setError((reason as Error).message) } }
  return <><header className="page-header"><div><span className="eyebrow">Manage / Identity</span><h1>Organizations</h1><p>Control shared ownership, organization status, and administrator memberships.</p></div>{isMasterView && <button className="button" onClick={() => setCreating(true)}>Create organization</button>}</header><ErrorBanner message={error} />{loading ? <PageLoading /> : items.length === 0 ? <Empty title="No visible organizations" detail="Create an organization or ask an administrator for membership." /> : <div className="organization-grid">{items.map((organization) => <article className="organization-card" key={organization.id}><div><strong><TruncatedText>{organization.name}</TruncatedText></strong><small title={organization.id}>{organization.id}</small></div><Badge tone={organization.status === 'active' ? 'good' : ''}>{organization.status}</Badge><div className="organization-member-total"><span>Total user members</span><strong>{organization.member_count ?? 0}</strong></div><dl><div><dt>Created</dt><dd>{formatDateTime(organization.created_at)}</dd></div><div><dt>Updated</dt><dd>{formatDateTime(organization.updated_at)}</dd></div></dl><div className="card-actions">{has('members:manage') && <button onClick={() => setMembersFor(organization)}>Manage members</button>}{isMasterView && <button onClick={() => void toggle(organization)}>{organization.status === 'active' ? 'Disable' : 'Enable'}</button>}</div></article>)}</div>}{creating && <CreateOrganizationModal onClose={() => setCreating(false)} onCreated={() => { setCreating(false); void load() }} />}{membersFor && <MembersModal organization={membersFor} users={users} onClose={() => setMembersFor(null)} />}</>
}

function CreateOrganizationModal({ onClose, onCreated }: { onClose: () => void; onCreated: () => void }) { const [name, setName] = useState(''); const [error, setError] = useState(''); return <Modal title="Create organization" onClose={onClose}><ErrorBanner message={error} /><Field label="Organization name"><input value={name} onChange={(event) => setName(event.target.value)} /></Field><div className="dialog-actions"><button className="button" disabled={!name.trim()} onClick={() => void createOrganization(name).then(onCreated).catch((reason: Error) => setError(reason.message))}>Create</button></div></Modal> }

function MembersModal({ organization, users, onClose }: { organization: Organization; users: User[]; onClose: () => void }) {
  const [members, setMembers] = useState<Membership[]>([]); const [userID, setUserID] = useState(''); const [role, setRole] = useState('member'); const [error, setError] = useState('')
  const load = useCallback(() => getMembers(organization.id).then((response) => setMembers(response.data)).catch((reason: Error) => setError(reason.message)), [organization.id])
  useEffect(() => { void load() }, [load])
  const availableUsers = users.filter((user) => !members.some((membership) => membership.user_id === user.id))
  const roleOptions = [{ value: 'member', label: 'Member' }, { value: 'admin', label: 'Administrator' }]
  return <Modal title={`${organization.name} members`} onClose={onClose}><ErrorBanner message={error} /><div className="member-list">{members.map((membership) => { const username = membership.username || users.find((user) => user.id === membership.user_id)?.username || membership.user_id; return <div key={membership.user_id}><span><strong title={username}>{username}</strong><small title={membership.user_id}>{membership.user_id}</small></span><SearchableSelect value={membership.role} options={roleOptions} onChange={(value) => void updateMember(organization.id, membership.user_id, value).then(load).catch((reason: Error) => setError(reason.message))} /><button className="danger-text" onClick={() => { if (window.confirm('Remove this membership?')) void deleteMember(organization.id, membership.user_id).then(load).catch((reason: Error) => setError(reason.message)) }}>Remove</button></div> })}</div>{availableUsers.length > 0 && <><h3 className="form-section-title">Add member</h3><div className="form-grid"><Field label="User"><SearchableSelect value={userID} onChange={setUserID} placeholder="Choose user" searchPlaceholder="Search users" options={availableUsers.map((user) => ({ value: user.id, label: user.username, meta: user.id }))} /></Field><Field label="Role"><SearchableSelect value={role} onChange={setRole} options={roleOptions} /></Field></div><div className="dialog-actions"><button className="button" disabled={!userID} onClick={() => void addMember(organization.id, userID, role).then(() => { setUserID(''); return load() }).catch((reason: Error) => setError(reason.message))}>Add member</button></div></>}</Modal>
}
