import { useCallback, useEffect, useState } from 'react'
import { addMember, createOrganization, deleteMember, getMembers, getOrganizations, getUsers, updateMember, updateOrganization } from '../api/client'
import type { Membership, Organization, User } from '../api/contracts'
import { Badge, Empty, ErrorBanner, Field } from '../components/Management'
import { Modal } from '../components/Modal'
import { PageLoading } from '../components/PageState'
import { SearchableSelect, TruncatedText } from '../components/SearchableSelect'
import { useSession } from '../context/SessionContext'
import { formatDateTime } from '../lib/format'

export function OrganizationsPage() {
  const { session, isMasterView, viewOrganizationID, viewUserID, has } = useSession(); const [items, setItems] = useState<Organization[]>([]); const [organizationCatalog, setOrganizationCatalog] = useState<Organization[]>([]); const [users, setUsers] = useState<User[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [creating, setCreating] = useState(false); const [membersFor, setMembersFor] = useState<Organization | null>(null)
  const load = useCallback(async () => { setLoading(true); try { const [organizations, catalog, userResponse] = await Promise.all([getOrganizations(), getOrganizations(true), getUsers().catch(() => ({ object: 'list' as const, data: [] }))]); setItems(viewOrganizationID ? organizations.data.filter((organization) => organization.id === viewOrganizationID) : organizations.data); setOrganizationCatalog(catalog.data); setUsers(userResponse.data) } catch (reason) { setError((reason as Error).message) } finally { setLoading(false) } }, [viewOrganizationID])
  useEffect(() => { void load() }, [load])
  const toggle = async (organization: Organization) => { try { await updateOrganization(organization.id, organization.name, organization.status === 'active' ? 'disabled' : 'active'); await load() } catch (reason) { setError((reason as Error).message) } }
  return <><header className="page-header"><div><span className="eyebrow">Manage / Identity</span><h1>Organizations</h1><p>Control shared ownership, organization status, and administrator memberships.</p></div>{(isMasterView || session?.principal_type === 'user' && session.user_role !== 'user') && <button className="button" onClick={() => setCreating(true)}>Create organization</button>}</header><ErrorBanner message={error} />{loading ? <PageLoading /> : items.length === 0 ? <Empty title="No visible organizations" detail="Create an organization or ask an administrator for membership." /> : <div className="organization-grid">{items.map((organization) => <article className="organization-card" key={organization.id}><div><strong><TruncatedText>{organization.name}</TruncatedText></strong><small title={organization.id}>{organization.id}</small></div><Badge tone={organization.status === 'active' ? 'good' : ''}>{organization.status}</Badge><div className="organization-member-total"><span>Total user members</span><strong>{organization.member_count ?? 0}</strong></div><dl><div><dt>Created</dt><dd>{formatDateTime(organization.created_at)}</dd></div><div><dt>Updated</dt><dd>{formatDateTime(organization.updated_at)}</dd></div></dl><div className="card-actions">{has('members:manage') && (!viewUserID || users.find((user) => user.id === viewUserID)?.memberships?.some((membership) => membership.organization_id === organization.id && membership.role === 'admin')) && <button onClick={() => setMembersFor(organization)}>Manage members</button>}{isMasterView && <button onClick={() => void toggle(organization)}>{organization.status === 'active' ? 'Disable' : 'Enable'}</button>}</div></article>)}</div>}{creating && <CreateOrganizationModal onClose={() => setCreating(false)} onCreated={() => { setCreating(false); void load() }} />}{membersFor && <MembersModal organization={membersFor} organizations={organizationCatalog} users={users} onClose={() => setMembersFor(null)} />}</>
}

function CreateOrganizationModal({ onClose, onCreated }: { onClose: () => void; onCreated: () => void }) { const [name, setName] = useState(''); const [error, setError] = useState(''); return <Modal title="Create organization" onClose={onClose}><ErrorBanner message={error} /><Field label="Organization name"><input value={name} onChange={(event) => setName(event.target.value)} /></Field><div className="dialog-actions"><button className="button" disabled={!name.trim()} onClick={() => void createOrganization(name).then(onCreated).catch((reason: Error) => setError(reason.message))}>Create</button></div></Modal> }

function MembersModal({ organization, organizations, users, onClose }: { organization: Organization; organizations: Organization[]; users: User[]; onClose: () => void }) {
  const [members, setMembers] = useState<Membership[]>([]); const [email, setEmail] = useState(''); const [foundUser, setFoundUser] = useState<User | null>(null); const [lookupState, setLookupState] = useState<'idle' | 'searching' | 'missing' | 'found'>('idle'); const [role, setRole] = useState('member'); const [error, setError] = useState('')
  const load = useCallback(() => getMembers(organization.id).then((response) => setMembers(response.data)).catch((reason: Error) => setError(reason.message)), [organization.id])
  useEffect(() => { void load() }, [load])
  const roleOptions = [{ value: 'member', label: 'Member' }, { value: 'admin', label: 'Administrator' }]
  useEffect(() => { const value = email.trim().toLowerCase(); setFoundUser(null); if (!value || !value.includes('@')) { setLookupState('idle'); return }; setLookupState('searching'); const timer = window.setTimeout(() => { void getUsers(value, organization.id).then((response) => { const exact = response.data.find((user) => user.username.toLowerCase() === value) ?? null; setFoundUser(exact); setLookupState(exact ? 'found' : 'missing') }).catch(() => setLookupState('missing')) }, 300); return () => window.clearTimeout(timer) }, [email, organization.id])
  const selectedAlreadyMember = foundUser ? members.some((membership) => membership.user_id === foundUser.id) : false
  const joinedOrganizations = foundUser?.memberships?.map((membership) => `${organizations.find((candidate) => candidate.id === membership.organization_id)?.name ?? membership.organization_id} (${membership.role})`) ?? []
  const submit = () => { if (!foundUser) return; void addMember(organization.id, foundUser.id, role).then(() => { setEmail(''); setFoundUser(null); setLookupState('idle'); setRole('member'); return load() }).catch((reason: Error) => setError(reason.message)) }
  return <Modal title={`${organization.name} members`} onClose={onClose}><ErrorBanner message={error} /><div className="member-list">{members.map((membership) => { const username = membership.username || users.find((user) => user.id === membership.user_id)?.username || membership.user_id; return <div key={membership.user_id}><span><strong title={username}>{username}</strong><small title={membership.user_id}>{membership.user_id}</small></span><SearchableSelect className={`role-select ${membership.role}`} value={membership.role} options={roleOptions.map((option) => ({ ...option, tone: option.value as 'member' | 'admin' }))} onChange={(value) => void updateMember(organization.id, membership.user_id, value).then(load).catch((reason: Error) => setError(reason.message))} /><button className="member-remove" onClick={() => { if (window.confirm('Remove this membership?')) void deleteMember(organization.id, membership.user_id).then(load).catch((reason: Error) => setError(reason.message)) }}>Remove</button></div> })}</div><section className="add-member-section"><h3 className="form-section-title">Add member by email</h3><div className="form-grid"><Field label="User email"><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="person@example.com" autoComplete="off" /></Field><Field label="Role"><SearchableSelect className={`role-select ${role}`} value={role} onChange={setRole} options={roleOptions.map((option) => ({ ...option, tone: option.value as 'member' | 'admin' }))} /></Field></div><div className={`member-lookup-result ${lookupState}`} aria-live="polite">{lookupState === 'searching' && <span>Searching for an exact email…</span>}{lookupState === 'missing' && <span>User not found</span>}{foundUser && <><div className="found-user"><strong>{foundUser.username}</strong><small>{foundUser.id}</small></div><div className="joined-organizations"><span>Organizations joined</span>{joinedOrganizations.length ? joinedOrganizations.map((item) => <em key={item}>{item}</em>) : <em>None</em>}</div>{selectedAlreadyMember && <span className="already-member">Already a member of {organization.name}</span>}</>}</div><div className="dialog-actions"><button className="button" disabled={!foundUser || selectedAlreadyMember || lookupState === 'searching'} onClick={submit}>Add member</button></div></section></Modal>
}
