package spa

import (
	"embed"
	"io/fs"
	"path"
	"strings"
)

// dist is generated by `npm run build` and committed so ordinary Go builds do
// not require Node.js at runtime.
//
//go:embed dist
var files embed.FS

func Index() ([]byte, error) {
	return fs.ReadFile(files, "dist/index.html")
}

func Asset(name string) ([]byte, error) {
	name = strings.TrimPrefix(name, "assets/")
	clean := path.Clean("/" + name)
	if clean == "/" || clean == "/." {
		return nil, fs.ErrNotExist
	}
	return fs.ReadFile(files, "dist/assets"+clean)
}
