-- Additive hot projections; JSON remains compatibility/detail storage.
ALTER TABLE usage_events ADD COLUMN user_id TEXT GENERATED ALWAYS AS (coalesce(json_extract(payload,'$.user_id'),'')) VIRTUAL;
ALTER TABLE usage_events ADD COLUMN organization_id TEXT GENERATED ALWAYS AS (coalesce(json_extract(payload,'$.organization_id'),'')) VIRTUAL;
ALTER TABLE usage_events ADD COLUMN agent_id TEXT GENERATED ALWAYS AS (coalesce(json_extract(payload,'$.agent_id'),'')) VIRTUAL;
ALTER TABLE usage_events ADD COLUMN conversation_id TEXT GENERATED ALWAYS AS (coalesce(json_extract(payload,'$.conversation_id'),'')) VIRTUAL;
ALTER TABLE usage_events ADD COLUMN model TEXT GENERATED ALWAYS AS (coalesce(json_extract(payload,'$.model'),'')) VIRTUAL;
ALTER TABLE usage_events ADD COLUMN api_key_id TEXT GENERATED ALWAYS AS (coalesce(json_extract(payload,'$.api_key_id'),'')) VIRTUAL;
ALTER TABLE usage_events ADD COLUMN provider TEXT GENERATED ALWAYS AS (coalesce(json_extract(payload,'$.provider'),'')) VIRTUAL;
ALTER TABLE usage_events ADD COLUMN credential_id TEXT GENERATED ALWAYS AS (coalesce(json_extract(payload,'$.credential_id'),'')) VIRTUAL;
ALTER TABLE usage_events ADD COLUMN application TEXT GENERATED ALWAYS AS (coalesce(json_extract(payload,'$.application'),'')) VIRTUAL;
ALTER TABLE usage_events ADD COLUMN environment TEXT GENERATED ALWAYS AS (coalesce(json_extract(payload,'$.environment'),'')) VIRTUAL;
ALTER TABLE usage_events ADD COLUMN workspace_id TEXT GENERATED ALWAYS AS (coalesce(json_extract(payload,'$.workspace_id'),'')) VIRTUAL;
ALTER TABLE usage_events ADD COLUMN run_id TEXT GENERATED ALWAYS AS (coalesce(json_extract(payload,'$.run_id'),'')) VIRTUAL;
ALTER TABLE usage_events ADD COLUMN parent_run_id TEXT GENERATED ALWAYS AS (coalesce(json_extract(payload,'$.parent_run_id'),'')) VIRTUAL;
ALTER TABLE usage_events ADD COLUMN trace_id TEXT GENERATED ALWAYS AS (coalesce(json_extract(payload,'$.trace_id'),'')) VIRTUAL;
ALTER TABLE usage_events ADD COLUMN logical_request_id TEXT GENERATED ALWAYS AS (coalesce(json_extract(payload,'$.logical_request_id'),'')) VIRTUAL;
ALTER TABLE usage_events ADD COLUMN usage_measurement TEXT GENERATED ALWAYS AS (coalesce(json_extract(payload,'$.usage_measurement'),'')) VIRTUAL;
ALTER TABLE usage_events ADD COLUMN accounting_state TEXT GENERATED ALWAYS AS (coalesce(json_extract(payload,'$.accounting_state'),'')) VIRTUAL;
ALTER TABLE usage_events ADD COLUMN prompt_tokens INTEGER GENERATED ALWAYS AS (coalesce(json_extract(payload,'$.prompt_tokens'),0)) VIRTUAL;
ALTER TABLE usage_events ADD COLUMN completion_tokens INTEGER GENERATED ALWAYS AS (coalesce(json_extract(payload,'$.completion_tokens'),0)) VIRTUAL;
ALTER TABLE usage_events ADD COLUMN cache_read_tokens INTEGER GENERATED ALWAYS AS (coalesce(json_extract(payload,'$.cache_read_tokens'),0)) VIRTUAL;
ALTER TABLE usage_events ADD COLUMN cache_write_tokens INTEGER GENERATED ALWAYS AS (coalesce(json_extract(payload,'$.cache_write_tokens'),0)) VIRTUAL;
ALTER TABLE usage_events ADD COLUMN cost_usd REAL GENERATED ALWAYS AS (coalesce(json_extract(payload,'$.cost_usd'),0)) VIRTUAL;
ALTER TABLE usage_events ADD COLUMN input_cost_usd REAL GENERATED ALWAYS AS (coalesce(json_extract(payload,'$.input_cost_usd'),0)) VIRTUAL;
ALTER TABLE usage_events ADD COLUMN output_cost_usd REAL GENERATED ALWAYS AS (coalesce(json_extract(payload,'$.output_cost_usd'),0)) VIRTUAL;
ALTER TABLE usage_events ADD COLUMN cache_read_cost_usd REAL GENERATED ALWAYS AS (coalesce(json_extract(payload,'$.cache_read_cost_usd'),0)) VIRTUAL;
ALTER TABLE usage_events ADD COLUMN cache_write_cost_usd REAL GENERATED ALWAYS AS (coalesce(json_extract(payload,'$.cache_write_cost_usd'),0)) VIRTUAL;
ALTER TABLE usage_events ADD COLUMN cache_hit INTEGER GENERATED ALWAYS AS (coalesce(json_extract(payload,'$.cache_hit'),0)) VIRTUAL;
ALTER TABLE usage_events ADD COLUMN priced INTEGER GENERATED ALWAYS AS (coalesce(json_extract(payload,'$.priced'),0)) VIRTUAL;
ALTER TABLE usage_events ADD COLUMN status_code INTEGER GENERATED ALWAYS AS (coalesce(json_extract(payload,'$.status_code'),0)) VIRTUAL;
ALTER TABLE usage_events ADD COLUMN duration_ms INTEGER GENERATED ALWAYS AS (coalesce(json_extract(payload,'$.duration_ms'),0)) VIRTUAL;
ALTER TABLE usage_events ADD COLUMN event_time TEXT GENERATED ALWAYS AS (substr((ts),1,19) || '.' || CASE WHEN substr((ts),20,1)='.' THEN substr(replace(substr((ts),21),'Z','') || '000000000',1,9) ELSE '000000000' END || 'Z') VIRTUAL;
ALTER TABLE usage_events ADD COLUMN accounting_time TEXT GENERATED ALWAYS AS (substr((CASE WHEN json_extract(payload,'$.accounting_ts') IS NULL OR json_extract(payload,'$.accounting_ts') LIKE '0001-%' THEN ts ELSE json_extract(payload,'$.accounting_ts') END),1,19) || '.' || CASE WHEN substr((CASE WHEN json_extract(payload,'$.accounting_ts') IS NULL OR json_extract(payload,'$.accounting_ts') LIKE '0001-%' THEN ts ELSE json_extract(payload,'$.accounting_ts') END),20,1)='.' THEN substr(replace(substr((CASE WHEN json_extract(payload,'$.accounting_ts') IS NULL OR json_extract(payload,'$.accounting_ts') LIKE '0001-%' THEN ts ELSE json_extract(payload,'$.accounting_ts') END),21),'Z','') || '000000000',1,9) ELSE '000000000' END || 'Z') VIRTUAL;
CREATE INDEX usage_events_user_accounting_idx ON usage_events(user_id,agent_id,accounting_time);
CREATE INDEX usage_events_normalized_order_idx ON usage_events(event_time DESC,id DESC);
CREATE INDEX api_key_owner_order_idx ON config_records(entity,json_extract(payload,'$.owner_user_id'),(coalesce(json_extract(payload,'$.context_organization_id'),'')='') DESC,(substr(json_extract(payload,'$.created_at'),1,19) || '.' || CASE WHEN substr(json_extract(payload,'$.created_at'),20,1)='.' THEN substr(replace(substr(json_extract(payload,'$.created_at'),21),'Z','') || '000000000',1,9) ELSE '000000000' END),key) WHERE entity='api_key';
